artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/ff1d20bd0b624ae5857ff2dd3dff3633/artifacts
end_time: 1613675968953
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: ff1d20bd0b624ae5857ff2dd3dff3633
run_uuid: ff1d20bd0b624ae5857ff2dd3dff3633
source_name: ''
source_type: 4
source_version: ''
start_time: 1613675856681
status: 3
tags: []
user_id: elozinoegonmwan
