artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/6607f9aa551649f4a0c8bf31a1a9a3e9/artifacts
end_time: 1613600147565
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 6607f9aa551649f4a0c8bf31a1a9a3e9
run_uuid: 6607f9aa551649f4a0c8bf31a1a9a3e9
source_name: ''
source_type: 4
source_version: ''
start_time: 1613600124276
status: 3
tags: []
user_id: elozinoegonmwan
