artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/5e91afb01f984df99348b54690e1baf1/artifacts
end_time: 1613598609008
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 5e91afb01f984df99348b54690e1baf1
run_uuid: 5e91afb01f984df99348b54690e1baf1
source_name: ''
source_type: 4
source_version: ''
start_time: 1613598564670
status: 3
tags: []
user_id: elozinoegonmwan
