artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/c5baa8bc049442348178738a7ef2c8e4/artifacts
end_time: 1613661833585
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: c5baa8bc049442348178738a7ef2c8e4
run_uuid: c5baa8bc049442348178738a7ef2c8e4
source_name: ''
source_type: 4
source_version: ''
start_time: 1613661751425
status: 3
tags: []
user_id: elozinoegonmwan
