artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/a69a8efdd668424e82bdf820633539e2/artifacts
end_time: 1613592082782
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: a69a8efdd668424e82bdf820633539e2
run_uuid: a69a8efdd668424e82bdf820633539e2
source_name: ''
source_type: 4
source_version: ''
start_time: 1613592069392
status: 3
tags: []
user_id: elozinoegonmwan
