artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/2943d58dcbfa4a408119a4ce5fbe396b/artifacts
end_time: null
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 2943d58dcbfa4a408119a4ce5fbe396b
run_uuid: 2943d58dcbfa4a408119a4ce5fbe396b
source_name: ''
source_type: 4
source_version: ''
start_time: 1613590895677
status: 1
tags: []
user_id: elozinoegonmwan
