artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/57983e4381e64bb1bf81b024e356beb6/artifacts
end_time: 1613768297795
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 57983e4381e64bb1bf81b024e356beb6
run_uuid: 57983e4381e64bb1bf81b024e356beb6
source_name: ''
source_type: 4
source_version: ''
start_time: 1613768277225
status: 3
tags: []
user_id: elozinoegonmwan
