artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/f75314c0d0414ee08708a2e8e6b7d08f/artifacts
end_time: 1613691649785
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: f75314c0d0414ee08708a2e8e6b7d08f
run_uuid: f75314c0d0414ee08708a2e8e6b7d08f
source_name: ''
source_type: 4
source_version: ''
start_time: 1613691329494
status: 3
tags: []
user_id: elozinoegonmwan
