artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/8e60f4f30db54b3eb6c82070106d67b0/artifacts
end_time: 1613595805855
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 8e60f4f30db54b3eb6c82070106d67b0
run_uuid: 8e60f4f30db54b3eb6c82070106d67b0
source_name: ''
source_type: 4
source_version: ''
start_time: 1613595795275
status: 3
tags: []
user_id: elozinoegonmwan
