artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/9344a293bf4941eda0e73444e11a83ec/artifacts
end_time: 1613768862483
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 9344a293bf4941eda0e73444e11a83ec
run_uuid: 9344a293bf4941eda0e73444e11a83ec
source_name: ''
source_type: 4
source_version: ''
start_time: 1613768843932
status: 3
tags: []
user_id: elozinoegonmwan
