artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/a0089f80680d449c93fb0fff4b9c201a/artifacts
end_time: 1613591468036
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: a0089f80680d449c93fb0fff4b9c201a
run_uuid: a0089f80680d449c93fb0fff4b9c201a
source_name: ''
source_type: 4
source_version: ''
start_time: 1613591454509
status: 3
tags: []
user_id: elozinoegonmwan
