artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/5cc4e976e2254b099d687c03cfc4dae3/artifacts
end_time: 1613708063043
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 5cc4e976e2254b099d687c03cfc4dae3
run_uuid: 5cc4e976e2254b099d687c03cfc4dae3
source_name: ''
source_type: 4
source_version: ''
start_time: 1613707881650
status: 3
tags: []
user_id: elozinoegonmwan
