artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/3c0d8806d1ed41e794cb8de43c260c46/artifacts
end_time: 1613676760431
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 3c0d8806d1ed41e794cb8de43c260c46
run_uuid: 3c0d8806d1ed41e794cb8de43c260c46
source_name: ''
source_type: 4
source_version: ''
start_time: 1613676646782
status: 3
tags: []
user_id: elozinoegonmwan
