artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/17a175c5d78e44f780bf75c241bc47c1/artifacts
end_time: 1613597221339
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 17a175c5d78e44f780bf75c241bc47c1
run_uuid: 17a175c5d78e44f780bf75c241bc47c1
source_name: ''
source_type: 4
source_version: ''
start_time: 1613597202006
status: 3
tags: []
user_id: elozinoegonmwan
