artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/aafd2e9c2e0a4efd83d827cc46c9cf30/artifacts
end_time: 1613715665981
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: aafd2e9c2e0a4efd83d827cc46c9cf30
run_uuid: aafd2e9c2e0a4efd83d827cc46c9cf30
source_name: ''
source_type: 4
source_version: ''
start_time: 1613712929073
status: 3
tags: []
user_id: elozinoegonmwan
