artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/49d6477c4285487d96bc349e7fd85fd3/artifacts
end_time: 1613596723939
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 49d6477c4285487d96bc349e7fd85fd3
run_uuid: 49d6477c4285487d96bc349e7fd85fd3
source_name: ''
source_type: 4
source_version: ''
start_time: 1613596696307
status: 3
tags: []
user_id: elozinoegonmwan
