artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/a596acc927e247449eb1fb8198b0ee75/artifacts
end_time: 1613770627669
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: a596acc927e247449eb1fb8198b0ee75
run_uuid: a596acc927e247449eb1fb8198b0ee75
source_name: ''
source_type: 4
source_version: ''
start_time: 1613770574620
status: 3
tags: []
user_id: elozinoegonmwan
