artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/2061c977ebbd46439bf52e65b9b52af0/artifacts
end_time: 1613591929426
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 2061c977ebbd46439bf52e65b9b52af0
run_uuid: 2061c977ebbd46439bf52e65b9b52af0
source_name: ''
source_type: 4
source_version: ''
start_time: 1613591914369
status: 3
tags: []
user_id: elozinoegonmwan
