artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/5b406a3dcaed45d49cf57d5fb19cca02/artifacts
end_time: 1613599425890
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 5b406a3dcaed45d49cf57d5fb19cca02
run_uuid: 5b406a3dcaed45d49cf57d5fb19cca02
source_name: ''
source_type: 4
source_version: ''
start_time: 1613599393135
status: 3
tags: []
user_id: elozinoegonmwan
