artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/5eefee7a085046bf8e65bf0edf5d0aef/artifacts
end_time: 1613771838235
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 5eefee7a085046bf8e65bf0edf5d0aef
run_uuid: 5eefee7a085046bf8e65bf0edf5d0aef
source_name: ''
source_type: 4
source_version: ''
start_time: 1613771785547
status: 3
tags: []
user_id: elozinoegonmwan
