artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/30575745783a4e0780532b2ab74025e8/artifacts
end_time: null
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 30575745783a4e0780532b2ab74025e8
run_uuid: 30575745783a4e0780532b2ab74025e8
source_name: ''
source_type: 4
source_version: ''
start_time: 1613707685701
status: 1
tags: []
user_id: elozinoegonmwan
