artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/3900119cbab94b16badf36804c300f28/artifacts
end_time: 1613597758261
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 3900119cbab94b16badf36804c300f28
run_uuid: 3900119cbab94b16badf36804c300f28
source_name: ''
source_type: 4
source_version: ''
start_time: 1613597734868
status: 3
tags: []
user_id: elozinoegonmwan
