artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/2cdc52e2a33e46b6b1fd2f941e177cc8/artifacts
end_time: 1613596471215
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 2cdc52e2a33e46b6b1fd2f941e177cc8
run_uuid: 2cdc52e2a33e46b6b1fd2f941e177cc8
source_name: ''
source_type: 4
source_version: ''
start_time: 1613596460622
status: 3
tags: []
user_id: elozinoegonmwan
