artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/46e2490f866f426884e0301ef39a4d3f/artifacts
end_time: 1613665133606
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 46e2490f866f426884e0301ef39a4d3f
run_uuid: 46e2490f866f426884e0301ef39a4d3f
source_name: ''
source_type: 4
source_version: ''
start_time: 1613665130078
status: 3
tags: []
user_id: elozinoegonmwan
