artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/08c2715678744a89b78db49ff3a525bc/artifacts
end_time: 1613707457862
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 08c2715678744a89b78db49ff3a525bc
run_uuid: 08c2715678744a89b78db49ff3a525bc
source_name: ''
source_type: 4
source_version: ''
start_time: 1613707436849
status: 3
tags: []
user_id: elozinoegonmwan
