artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/0467d4c0da8246d981be61eff3df2acc/artifacts
end_time: 1613769261317
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 0467d4c0da8246d981be61eff3df2acc
run_uuid: 0467d4c0da8246d981be61eff3df2acc
source_name: ''
source_type: 4
source_version: ''
start_time: 1613769242622
status: 3
tags: []
user_id: elozinoegonmwan
