artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/073ceead03544e21bb7bf49aa4e43b1d/artifacts
end_time: 1613599573055
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 073ceead03544e21bb7bf49aa4e43b1d
run_uuid: 073ceead03544e21bb7bf49aa4e43b1d
source_name: ''
source_type: 4
source_version: ''
start_time: 1613599528095
status: 3
tags: []
user_id: elozinoegonmwan
