artifact_uri: file:///Users/elozinoegonmwan/PycharmProjects/question_generation/mlruns/0/bb25c091c181457c97189a9ea42d7890/artifacts
end_time: 1613668464715
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: bb25c091c181457c97189a9ea42d7890
run_uuid: bb25c091c181457c97189a9ea42d7890
source_name: ''
source_type: 4
source_version: ''
start_time: 1613668408954
status: 3
tags: []
user_id: elozinoegonmwan
